services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Брокер сообщений Redis
  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 3. Бэкенд (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: sh -c "export PATH=$PATH:/root/.local/bin && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - USE_CELERY=${USE_CELERY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 4. Воркер Celery
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: sh -c "export PATH=$PATH:/root/.local/bin && python -m celery -A config worker --loglevel=info --concurrency=4 -E"
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - USE_CELERY=${USE_CELERY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 5. Фронтенд (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80" # Было "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: