server {
    listen 8000;
    server_name _;

    root /usr/share/nginx/html;

    # 1. Django static files (for /admin/)
    location /static/ {
        alias /app/staticfiles/;
    }

    # 2. Django API endpoints
    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Django Admin
    location /admin/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

   # 4. React SPA routes (frontend)
    # Запросы на главную отдают index.html
    location = / {
        try_files /index.html =404;
    }

    # Для дашборда и биллинга ловим любые вложенные пути (например, /dashboard/)
    location ~ ^/(dashboard|billing) {
        try_files /index.html =404;
    }

    # Статика фронтенда (JS, CSS, картинки)
    location /assets/ {
        try_files $uri =404;
    }

    # 5. All other requests go to Django for short link redirection (e.g. /my-slug)
    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}