# Generated by Django 6.0.6 on 2026-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0002_linkanalytics_ip_address_alter_shortlink_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Is custom slug'),
        ),
    ]
