# Generated by Django 6.0.6 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_shortlink_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
