# Generated by Django 6.0.6 on 2026-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_pricingplan_alter_user_managers_usersubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(choices=[('Free', 'Свободный (Free)'), ('Popular', 'Популярный (Popular)'), ('Pro', 'Профессиональный (Pro)')], default='Free', max_length=100, verbose_name="Plan's name"),
        ),
    ]
