# Generated by Django 6.0.6 on 2026-06-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_pricingplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Plan's name"),
        ),
    ]
