# Generated by Django 6.0.6 on 2026-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_pricingplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
    ]
