# Generated by Django 6.0.6 on 2026-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_usersubscriptions_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='name',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='description (EN)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='description (UK)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_disabled_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Disabled features (EN)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_disabled_uk',
            field=models.JSONField(blank=True, default=list, verbose_name='Disabled features (UK)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_en',
            field=models.JSONField(default=list, verbose_name='Enabled features (EN)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features_uk',
            field=models.JSONField(default=list, verbose_name='Enabled features (UK)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name="Plan's name (EN)"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='name_uk',
            field=models.CharField(default='', max_length=100, verbose_name="Plan's name (UK)"),
        ),
    ]
