# Generated by Django 6.0.6 on 2026-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_remove_pricingplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Highlight plan (Popular)'),
        ),
    ]
