# Generated by Django 6.0.6 on 2026-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_pricingplan_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_custom_slug_allowed',
            field=models.BooleanField(default=False, verbose_name='Allow custom slug (short code)'),
        ),
    ]
