# Generated by Django 6.0.6 on 2026-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_pricingplan_is_custom_slug_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='max_custom_slug_allowed',
            field=models.IntegerField(default=0, verbose_name='max_custom_slug_allowed'),
        ),
    ]
