# Generated by Django 6.0.6 on 2026-07-16 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_pricingplan_max_custom_slug_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='current_custom_slugs_count',
            field=models.IntegerField(default=0, verbose_name='Current custom slugs count'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='current_links_count',
            field=models.IntegerField(default=0, verbose_name='Current links count'),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
