# Generated by Django 6.0.6 on 2026-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_usersubscriptions_current_custom_slugs_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_default_free',
            field=models.BooleanField(default=False, verbose_name='Is default free plan'),
        ),
    ]
